apiVersion: v1
kind: Service
metadata:
  name: grafeas-service
spec:
  ports:
    - port: 8080
      targetPort: 8090
      protocol: TCP
  selector:
      app: grafeas
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafeas
spec:
  template:
    metadata:
      labels:
        app: grafeas
    spec:
      containers:
        - name: grafeas
          image: "gcr.io/hightowerlabs/grafeas:0.0.1"
          imagePullPolicy: Always
